title: BYEONGSU KIM
description: "Satellite - jekyll blog theme"
url: "https://codingbus821.github.io"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: kbsu147@naver.com
github_username: codingbus821
# twitter_username: twitter
# instagram_username: instagram
linkedin_username: kimbyeongsu
# facebook_username: facebook

# External API
giscus_repo: "codingbus821/codingbus821.github.io"
giscus_repoId: "R_kgDOPqIpJw"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOPqIpJ84CvB8P"
goatcounter_code: codingbus821
google_analytics:
google_site_verification: "6kcctMmbEf_PoOkDKP5lDL-GaPNkxW2DJlcYYtoMgnI"

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
